[package]
name = "fyrer-process"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "OS process primitives for fyrer"
repository.workspace = true

[dependencies]
fyrer-core.workspace = true
anyhow = "1.0"
tokio = { version = "1.30", features = ["full"] }
libc = "0.2"
