#!/usr/bin/env python3
"""Generate markdown docs into ../docs from the cli package.

Runs with cwd=scripts to demonstrate fyrer's per-task `cwd` option.
"""

import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "docs"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "index.md").write_text(
        "# acme-corp docs\n\n"
        "Generated by the `cli:docs` task (runs with `cwd: scripts`).\n"
    )
    print(f"[cli] docs -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())