[package]
name = "fyrer-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "UI reporters for fyrer"
repository.workspace = true

[dependencies]
fyrer-core.workspace = true
fyrer-engine.workspace = true
fyrer-log.workspace = true
anyhow = "1.0"
tokio = { version = "1.30", features = ["full"] }
ratatui = "0.30.2"
crossterm = "0.29.0"
ansi-to-tui = "8.0.1"
owo-colors = "4.3.0"
chrono = "0.4"
